
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "EQ GE ID INTLIT LE NEQ\n    Equality : Relation\n             | Relation EquOp Relation\n    \n    EquOp : EQ\n          | NEQ\n    \n    Relation : Addition\n             | Addition RelOp Addition\n    \n    RelOp : '<'\n          | LE\n          | '>'\n          | GE \n    \n    Addition : Term\n             | Addition AddOp Term\n    \n    AddOp : '+'\n          | '-'\n    \n    Term : Factor\n         | Term MulOp Factor\n    \n    MulOp : '*'\n          | '/'\n          | '%'\n    \n    Factor : UnaryOp Primary\n           | Primary\n    \n    UnaryOp : '-'\n            | '!'\n    \n    Primary : INTLIT \n            | '(' Equality ')'\n    "
    
_lr_action_items = {'-':([0,3,4,5,7,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,30,31,32,33,],[8,22,-11,-15,-21,-24,8,8,-3,-4,8,8,-7,-8,-9,-10,-13,-14,8,-17,-18,-19,-20,22,-12,-16,-25,]),'!':([0,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,],[9,9,9,-3,-4,9,9,-7,-8,-9,-10,-13,-14,9,-17,-18,-19,]),'INTLIT':([0,6,8,9,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,],[10,10,-22,-23,10,10,-3,-4,10,10,-7,-8,-9,-10,-13,-14,10,-17,-18,-19,]),'(':([0,6,8,9,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,],[11,11,-22,-23,11,11,-3,-4,11,11,-7,-8,-9,-10,-13,-14,11,-17,-18,-19,]),'$end':([1,2,3,4,5,7,10,27,29,30,31,32,33,],[0,-1,-5,-11,-15,-21,-24,-20,-2,-6,-12,-16,-25,]),')':([2,3,4,5,7,10,27,28,29,30,31,32,33,],[-1,-5,-11,-15,-21,-24,-20,33,-2,-6,-12,-16,-25,]),'EQ':([2,3,4,5,7,10,27,30,31,32,33,],[13,-5,-11,-15,-21,-24,-20,-6,-12,-16,-25,]),'NEQ':([2,3,4,5,7,10,27,30,31,32,33,],[14,-5,-11,-15,-21,-24,-20,-6,-12,-16,-25,]),'<':([3,4,5,7,10,27,31,32,33,],[17,-11,-15,-21,-24,-20,-12,-16,-25,]),'LE':([3,4,5,7,10,27,31,32,33,],[18,-11,-15,-21,-24,-20,-12,-16,-25,]),'>':([3,4,5,7,10,27,31,32,33,],[19,-11,-15,-21,-24,-20,-12,-16,-25,]),'GE':([3,4,5,7,10,27,31,32,33,],[20,-11,-15,-21,-24,-20,-12,-16,-25,]),'+':([3,4,5,7,10,27,30,31,32,33,],[21,-11,-15,-21,-24,-20,21,-12,-16,-25,]),'*':([4,5,7,10,27,31,32,33,],[24,-15,-21,-24,-20,24,-16,-25,]),'/':([4,5,7,10,27,31,32,33,],[25,-15,-21,-24,-20,25,-16,-25,]),'%':([4,5,7,10,27,31,32,33,],[26,-15,-21,-24,-20,26,-16,-25,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Equality':([0,11,],[1,28,]),'Relation':([0,11,12,],[2,2,29,]),'Addition':([0,11,12,15,],[3,3,3,30,]),'Term':([0,11,12,15,16,],[4,4,4,4,31,]),'Factor':([0,11,12,15,16,23,],[5,5,5,5,5,32,]),'UnaryOp':([0,11,12,15,16,23,],[6,6,6,6,6,6,]),'Primary':([0,6,11,12,15,16,23,],[7,27,7,7,7,7,7,]),'EquOp':([2,],[12,]),'RelOp':([3,],[15,]),'AddOp':([3,30,],[16,16,]),'MulOp':([4,31,],[23,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Equality","S'",1,None,None,None),
  ('Equality -> Relation','Equality',1,'p_Equality','analisis.py',48),
  ('Equality -> Relation EquOp Relation','Equality',3,'p_Equality','analisis.py',49),
  ('EquOp -> EQ','EquOp',1,'p_EquOp','analisis.py',59),
  ('EquOp -> NEQ','EquOp',1,'p_EquOp','analisis.py',60),
  ('Relation -> Addition','Relation',1,'p_Relation','analisis.py',67),
  ('Relation -> Addition RelOp Addition','Relation',3,'p_Relation','analisis.py',68),
  ('RelOp -> <','RelOp',1,'p_RelOp','analisis.py',77),
  ('RelOp -> LE','RelOp',1,'p_RelOp','analisis.py',78),
  ('RelOp -> >','RelOp',1,'p_RelOp','analisis.py',79),
  ('RelOp -> GE','RelOp',1,'p_RelOp','analisis.py',80),
  ('Addition -> Term','Addition',1,'p_Addition','analisis.py',86),
  ('Addition -> Addition AddOp Term','Addition',3,'p_Addition','analisis.py',87),
  ('AddOp -> +','AddOp',1,'p_AddOp','analisis.py',96),
  ('AddOp -> -','AddOp',1,'p_AddOp','analisis.py',97),
  ('Term -> Factor','Term',1,'p_Term','analisis.py',103),
  ('Term -> Term MulOp Factor','Term',3,'p_Term','analisis.py',104),
  ('MulOp -> *','MulOp',1,'p_MulOp','analisis.py',113),
  ('MulOp -> /','MulOp',1,'p_MulOp','analisis.py',114),
  ('MulOp -> %','MulOp',1,'p_MulOp','analisis.py',115),
  ('Factor -> UnaryOp Primary','Factor',2,'p_Factor','analisis.py',121),
  ('Factor -> Primary','Factor',1,'p_Factor','analisis.py',122),
  ('UnaryOp -> -','UnaryOp',1,'p_UnaryOp','analisis.py',134),
  ('UnaryOp -> !','UnaryOp',1,'p_UnaryOp','analisis.py',135),
  ('Primary -> INTLIT','Primary',1,'p_Primary','analisis.py',141),
  ('Primary -> ( Equality )','Primary',3,'p_Primary','analisis.py',142),
]
